name: get_cli
description: A sample command-line application.
version: 2.0.0
homepage: https://github.com/CpdnCristiano/get_cli

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  ansicolor: ^1.0.2
  process_run: ^0.10.12+1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

executables:
  get: main